//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSharingWeb.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSharingWeb.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most downloaded uploads are displayed here.
        /// </summary>
        public static string header_desc {
            get {
                return ResourceManager.GetString("header_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Uploads.
        /// </summary>
        public static string header_title {
            get {
                return ResourceManager.GetString("header_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search,download And upload Images,Videos,pdf files.
        /// </summary>
        public static string hero_desc {
            get {
                return ResourceManager.GetString("hero_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File sharing Website.
        /// </summary>
        public static string hero_title {
            get {
                return ResourceManager.GetString("hero_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For Upload.
        /// </summary>
        public static string search_upload {
            get {
                return ResourceManager.GetString("search_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a great place to tell people more about your services and peak,their interest. Last year our latest work album.
        /// </summary>
        public static string search_upload_desc {
            get {
                return ResourceManager.GetString("search_upload_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Video.
        /// </summary>
        public static string watch_video {
            get {
                return ResourceManager.GetString("watch_video", resourceCulture);
            }
        }
    }
}
